---
name: cmdblog-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: lint
        run: pylint cmdblog_backend
      - name: unit test
        run: python manage.py test
