---
name: cmdblog-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install packages used only in ci
        run: pip install pylint pylint-django mypy
      - name: install dependencies
        run: |
          pip install -r requirements.txt -r requirements_dev.txt
      - name: lint
        run: pylint cmdblog_backend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install packages used only in ci
        run: pip install pylint pylint-django mypy
      - name: install dependencies
        run: |
          pip install -r requirements.txt -r requirements_dev.txt
      - name: unit test
        run: python manage.py test
