---
name: cmdblog-release
on:
  push:
    tags:
      - "v*"

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - name: get tag name
        id: tag_info
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
        with:
          path: cmdblog-backend
      - uses: actions/checkout@v2
        with:
          repository: cmdblog/cmdblog-schema
          path: cmdblog-schema
      - name: set up git
        run: |
          git config --global user.email "cmdblog-mu@github.com"
          git config --global user.name "cmdblog Machine User"
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt -r requirements_dev.txt
        working-directory: cmdblog-backend
      - name: generate schema
        run: make TAG=${{ github.ref }} openapi-schema.yaml
        working-directory: cmdblog-backend
      - name: copy schema file
        run: cp cmdblog-backend/openapi-schema.yaml cmdblog-schema/openapi-schema.yaml
      - name: commit and push
        env:
          GIT_SSH_COMMAND: ssh -i deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git add openapi-schema.yaml
          git commit -m "tag: ${{ steps.tag_info.output.TAG }}"
          echo ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          git push
        working-directory: cmdblog-schema
      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_info.output.TAG }}
          release_name: Release ${{ steps.tag_info.output.TAG }}
